name: Deploy static content to Pages

on:
  push:
    branches: ["main"] # 만약 기본 브랜치명이 master라면 "master"로 수정

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # 저장소 루트의 HTML, CSS, JS, content 등 모든 정적 파일을 업로드

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4